baseURL = "https://campgesher.com/"
title = "Camp Gesher"

enableEmoji = true
enableRobotsTXT = true
hrefTargetBlank = true
googleAnalytics = "UA-41397217-1"
disableKinds = ["taxonomy", "section", "taxonomyTerm"]

[imaging]
quality = 95

[[menu.main]]
name = "Donate"
url = "https://www.canadahelps.org/en/charities/camp-gesher/"
weight = 0

[[menu.main]]
name = "Reconnect"
parent = "Alumni"
url = "https://facebook.com/campgesher"

[[menu.main]]
name = "Seminars and Camp"
parent = "Register"
url = "https://gesher.campbrainregistration.com/"

[[menu.main]]
name = "Israel Weekend"
parent = "Register"
url = "https://gesher.campbrainregistration.com/"

[[menu.main]]
name = "Camp Grant"
parent = "Register"
url = "https://jewishtoronto.com/cje/camp"

[[menu.main]]
name = "Guide to Gesher"
parent = "Preparation"
url = "/docs/2018/summer-2018-guide-to-gesher.pdf"

[[menu.main]]
name = "Letter to Parents"
parent = "Preparation"
url = "/docs/2018/summer-2018-parents-letter.pdf"
