[context.production.environment]
HUGO_VERSION = "0.55.4"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.4"

[[redirects]]
from = "https://campgesher.netlify.com/*"
to = "https://campgesher.com/:splat"
force = true

[[headers]]
for = "*"
[headers.values]
"Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
"Content-Security-Policy" = "default-src https:"
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"X-XSS-Protection" = "1; mode=block"
