[context.production.environment]
HUGO_VERSION = "0.45"

[context.deploy-preview.environment]
HUGO_VERSION = "0.45"
NETLIFY_TEST = "true"

[[redirects]]
from = "https://campgesher.netlify.com/*"
to = "https://campgesher.com/:splat"
force = true
