[context.production.environment]
HUGO_VERSION = "0.67.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.67.0"

# [[redirects]]
# from = "https://campgesher.netlify.com/*"
# to = "https://campgesher.com/:splat"
# force = true

[[headers]]
for = "*"
[headers.values]
"Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
"Content-Security-Policy" = "object-src 'none'; script-src https: 'unsafe-inline'; style-src https: 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"X-XSS-Protection" = "1; mode=block"
"Service-Worker-Allowed" = "/"
