---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/history
  label: History
  create: all
  match: "**/*"
- type: directory
  path: content/health-and-safety
  label: Health and safety
  create: all
  match: "**/*"
- type: directory
  path: content/food-nutrition
  label: Food nutrition
  create: all
  match: "**/*"
- type: directory
  path: content/rentals
  label: Rentals
  create: all
  match: "**/*"
- type: directory
  path: content/visiting-camp
  label: Visiting camp
  create: all
  match: "**/*"
- type: directory
  path: content/camp-director
  label: Camp director
  create: all
  match: "**/*"
- type: directory
  path: content/activities
  label: Activities
  create: all
  match: "**/*"
- type: directory
  path: content/alumni-archive
  label: Alumni archive
  create: all
  match: "**/*"
- type: directory
  path: content/daily-schedule
  label: Daily schedule
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
